//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DMP609VC.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_DMP609VC_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DLG_FORCE_POWER_MONITOR     129
#define IDD_DIALOG_KEY_INPUT            130
#define IDC_AD_DATA                     1000
#define IDC_AD_V                        1001
#define IDC_AD                          1002
#define IDC_SD_AD                       1003
#define IDC_FER                         1004
#define IDC_TI_AD                       1005
#define IDC_R_AD                        1006
#define IDC_RA1                         1010
#define IDC_CH1                         1011
#define IDC_RA2                         1012
#define IDC_RA3                         1013
#define IDC_RA4                         1014
#define IDC_RA5                         1015
#define IDC_RA6                         1016
#define IDC_RA7                         1017
#define IDC_RA8                         1018
#define IDC_RA9                         1019
#define IDC_RA10                        1020
#define IDC_RA11                        1021
#define IDC_RA12                        1022
#define IDC_RA13                        1023
#define IDC_RA14                        1024
#define IDC_RA15                        1025
#define IDC_RA16                        1026
#define IDC_CH2                         1027
#define IDC_CH3                         1028
#define IDC_CH4                         1029
#define IDC_CH5                         1030
#define IDC_CH6                         1031
#define IDC_CH7                         1032
#define IDC_CH8                         1033
#define IDC_CH9                         1034
#define IDC_CH10                        1035
#define IDC_CH11                        1036
#define IDC_CH12                        1037
#define IDC_CH13                        1038
#define IDC_CH14                        1039
#define IDC_CH15                        1040
#define IDC_CH16                        1041
#define IDC_SC_AD                       1042
#define IDC_DA1                         1043
#define IDC_DA2                         1044
#define IDC_DO1                         1045
#define IDC_DO1_16                      1046
#define IDC_IO1                         1047
#define IDC_IO1_DATA1                   1048
#define IDC_IO1_16                      1049
#define IDC_IO1_16_DATA                 1050
#define IDC_RA21                        1052
#define IDC_RA22                        1053
#define IDC_RA23                        1056
#define IDC_COMBO_DA1_ANALOG_WAVE       1057
#define IDC_EDIT_FREQUENCY_ANALOG_OUT   1058
#define IDC_CHECK_FLAG_ENABLE_ANALOG_WAVE 1059
#define IDC_BUTTON_START_FORCE_POWER_MONITOR 1060
#define IDC_STATIC_TITLE_BONDING_MONITOR_1STB 1061
#define IDC_STATIC_BOND_FORCE_MONITOR_1STBOND 1062
#define IDC_STATIC_BOND_POWER_MONITOR_1STBOND 1063
#define IDC_STATIC_TITLE_BONDING_MONITOR_2NDB 1064
#define IDC_STATIC_BOND_POWER_MONITOR_2NDBOND 1065
#define IDC_STATIC_BOND_FORCE_MONITOR_2NDBOND 1066
#define IDC_BUTTON_PAUSE_PF_MONITOR_DLG 1067
#define IDC_BUTTON_SAVE_PF_MONITOR_DLG  1068
#define IDC_BUTTON_LOAD_PF_MONITOR_DLG  1069
#define IDC_COMBO_USER_LEVEL_PF_MONITOR_DLG 1070
#define IDC_CCOMBO_RUNNING_MODE_PF_MONITOR_DLG 1071
#define IDC_COMBO3                      1072
#define IDC_COMBO_FPMD_VERIFY_THRESHOLD_IMPEDANCE_OHM 1072
#define IDC_CCOMBO_POWER_MODE_PF_MONITOR_DLG 1073
#define IDC_STATIC_CAPTURE_TRIGGER_FLAG_PF_MONITOR_DLG 1074
#define ID_BTN_EXIT_FP_MONITOR_DLG      1075
#define IDC_STATIC_GOLDEN_WAVEFORM_STATISTIC 1076
#define IDC_CHECK_FPMD_FLAG_SHOWN_GOLDEN_WAVEFORM 1077
#define IDC_COMBO_VERIFY_MODE_PF_MONITOR_DLG 1078
#define IDC_COMBO_FPMD_VERIFY_THRESHOLD_FORCE_GRAM 1079
#define IDC_COMBO_FPMD_VERIFY_THRESHOLD_POWER_mW 1080
#define IDC_STATIC_FOPEM_DISPLAY_DATE_TIME 1081
#define IDC_STATIC_DISPLAY_CHECK_RESULT_FOPEM_DLG 1082
#define IDC_STATIC_ROLLING_DISPLAY_MAX_FORCE 1083
#define IDC_STATIC_ROLLING_DISPLAY_MAX_POWER_mW 1084
#define IDC_STATIC_ROLLING_DISPLAY_MAX_IMPEDANCE 1085
#define IDC_BUTTON1                     1086
#define IDC_BUTTON_FOPEM_DLG_AUTO_CHECK_CALIBRATE 1086
#define IDC_BUTTON_DLG_KEY_0            1086
#define IDC_STATIC_CHECK_THRESHOLD_IMPEDANCE 1087
#define IDC_STATIC_FOPEM_DLG_USER_LEVEL 1088
#define IDC_STATIC_DLG_FPMD_MODE        1089
#define IDC_STATIC_DLG_FPMD_VERIFY_RESULT 1090
#define IDC_STATIC_ROLLING_DISPLAY_GOLD_FORCE 1091
#define IDC_STATIC_ROLLING_DISPLAY_LOW_THRESHOLD_FORCE 1092
#define IDC_STATIC_ROLLING_DISPLAY_GOLD_POWER_mW 1093
#define IDC_STATIC_ROLLING_DISPLAY_MIN_POWER_mW 1094
#define IDC_EDIT_DLG_KEY_INPUT_SHOW_TEXT 1095
#define IDC_BUTTON_DLG_KEY_2            1096
#define IDC_BUTTON_DLG_KEY_1            1097
#define IDC_BUTTON_DLG_KEY_3            1098
#define IDC_BUTTON_DLG_KEY_4            1099
#define IDC_BUTTON_DLG_KEY_5            1100
#define IDC_BUTTON_DLG_KEY_6            1101
#define IDC_BUTTON_DLG_KEY_7            1102
#define IDC_BUTTON_DLG_KEY_8            1103
#define IDC_BUTTON_DLG_KEY_9            1104
#define IDC_CHECK_DLG_SHOW_NUMBER       1105
#define ID_BUTTON_DLG_KEY_PAD_OK        1106
#define IDC_BUTTON12                    1107
#define ID_BUTTON_DLG_KEY_PAD_CLEAR     1107
#define IDC_STATIC_TH                   1108
#define IDC_STATIC_THRESHOLD_AND_FORCE_ 1108
#define IDC_STATIC_POWER_THRESHOLD      1109
#define IDC_SLIDER_FORCE_DISPLAY_OFFSET_FPMD_DLG 1112
#define IDC_SLIDER_POWER_DISPLAY_OFFSET_FPMD_DLG 1113
#define IDC_STATIC_OFFSET_DISPLAY       1114
#define IDC_STATIC_OFFSET_DISPLAY_FPMD_DLG 1114
#define IDC_STATIC_FORCE_OFFSET_VALUE_FPMD_DLG 1115
#define IDC_STATIC_POWER_OFFSET_VALUE_FPMD_DLG 1116

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
